artifacts_root: artifacts

data_ingestion:
    root_dir: artifacts/data_ingestion
    service: s3
    region: us-east-1
    bucket_name: reynaml
    aws_file: file1.csv
    download_path: artifacts/data_ingestion/data.csv
    aws_access_key_id: 
    aws_secret_access_key: 